name: Run Tests

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          # Базовые настройки БД
          echo "POSTGRES_DB=test_db" >> .env
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_PASSWORD=postgres" >> .env
          echo "POSTGRES_HOST=db" >> .env
          echo "POSTGRES_PORT=5432" >> .env
          echo "DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/test_db" >> .env
          
          # Redis и Celery
          echo "REDIS_URL=redis://redis:6379/0" >> .env
          
          # Настройки безопасности
          echo "SECRET_KEY=test_secret_key_fixed_for_ci_123" >> .env
          echo "ALGORITHM=HS256" >> .env
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=30" >> .env
          
          # Настройки почты (теперь не будут вызывать ValidationError)
          echo "SMTP_HOST=smtp.mailtrap.io" >> .env
          echo "SMTP_PORT=2525" >> .env
          echo "SMTP_USER=test_user" >> .env
          echo "SMTP_PASSWORD=test_password" >> .env
          echo "SMTP_FROM_EMAIL=noreply@test.com" >> .env
          
          # Настройки PgAdmin
          echo "PGADMIN_EMAIL=admin@test.com" >> .env
          echo "PGADMIN_PASSWORD=admin" >> .env

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Wait for services to be ready
        run: |
          # Даем время БД и Redis полностью инициализироваться
          echo "Waiting for database to start..."
          sleep 15

      - name: Run Pytest inside container
        run: |
          # Запуск тестов. Флаг -T отключает интерактивный режим (TTY)
          docker compose exec -T app pytest

      - name: Stop containers
        if: always()
        run: docker compose down

        